"""init_schema.

Revision ID: 45028527ca98
Revises: 2e869ac49abe
Create Date: 2026-02-04 18:58:41.432221+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45028527ca98"
down_revision: Union[str, Sequence[str], None] = "2e869ac49abe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "survey_sessions",
        "status",
        existing_type=sa.VARCHAR(length=11),
        type_=sa.Enum(
            "IN_PROGRESS", "WAITING_FOR_CONFIRMATION", "COMPLETED", "ABANDONED", name="surveystatus", native_enum=False
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "survey_sessions",
        "status",
        existing_type=sa.Enum(
            "IN_PROGRESS", "WAITING_FOR_CONFIRMATION", "COMPLETED", "ABANDONED", name="surveystatus", native_enum=False
        ),
        type_=sa.VARCHAR(length=11),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
